name: ci-pr

on:
  pull_request:
    branches:
    - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
    - uses: actions/checkout@v1
    - name: Display system info (linux)
      run: |
        set -e
        hostname
        whoami
        cat /etc/*release
        lscpu
        free
        df -h
        pwd
        docker info
        docker version
    - name: Code Coverage
      run: |
        set -e
        apk add --no-cache git make || sudo apt-get install -y git make
        sudo -s /bin/sh -c 'make test' # Force make to run docker under root user
        bash <(curl -s https://codecov.io/bash)
